import { describe, expect, test } from "bun:test";
import {
  collectReferencedPrs,
  generateExternalSummary,
  type ExternalDossier,
} from "../src/summary/external";
import type { LLMProvider } from "../src/llm/provider";

/**
 * The OSS "watch" rail posts gx summaries onto public third-party pull requests
 * and shares PR_SUMMARY_SYSTEM_PROMPT with the internal one. Rules written for
 * the internal rail therefore land on public output, so what this rail sends is
 * asserted here rather than assumed. No model is contacted: the provider is a
 * stub that records the prompts and returns a fixed, valid summary.
 */

const VALID_SUMMARY = [
  "> 🟡 👀 **Careful pass** — touches the shared DNS resolver guard",
  "",
  "Tightens the SSRF guard so redirects are re-validated.",
  "",
  "## Blast Radius",
  "",
  "🟡 MEDIUM (2 file(s), 1 area(s), +40/-6 lines).",
  "Shared network path; every outbound fetch goes through it.",
  "",
  "## Notable Changes",
  "",
  "- Re-validates the host after each redirect",
  "  Attribution: codebase `src/fetch.ts:88`",
  "- Restores the check dropped in #91",
  "  Attribution: previous-prs PR #91",
  "",
  "*Generated by gx.*",
].join("\n");

function recordingProvider(): {
  provider: LLMProvider;
  prompts: Array<{ system: string; user: string }>;
} {
  const prompts: Array<{ system: string; user: string }> = [];
  const provider: LLMProvider = {
    complete: async (system: string, user: string) => {
      prompts.push({ system, user });
      return { text: VALID_SUMMARY, model: "stub-model" };
    },
  } as LLMProvider;
  return { provider, prompts };
}

function dossier(overrides: Partial<ExternalDossier> = {}): ExternalDossier {
  return {
    repoFullName: "bitwarden/clients",
    number: 104,
    url: "https://github.com/bitwarden/clients/pull/104",
    title: "Re-validate redirect hosts",
    state: "open",
    baseRef: "main",
    headRef: "fix/ssrf-redirect",
    headSha: "cafebabecafebabecafebabecafebabecafebabe",
    additions: 40,
    deletions: 6,
    changedFiles: 2,
    files: [
      { path: "src/fetch.ts", additions: 34, deletions: 6 } as never,
      { path: "src/fetch.spec.ts", additions: 6, deletions: 0 } as never,
    ],
    body: "Restores the guard dropped in #91.",
    referencedPrs: [91],
    coverage: null,
    diff: "diff --git a/src/fetch.ts b/src/fetch.ts\n@@ -1 +1 @@\n+guard\n",
    ...overrides,
  };
}

describe("external OSS summaries", () => {
  test("states GitHub's exact line counts as the authoritative Diff stats line", async () => {
    // The shared system prompt omits the +X/-Y figure when no "Diff stats"
    // line is present. This rail has exact totals from the GitHub API, so it
    // must present them in the form the prompt reads — otherwise accurate
    // counts silently disappear from a public comment.
    const { provider, prompts } = recordingProvider();
    await generateExternalSummary(dossier(), "oss-outreach", provider);

    const user = prompts[0]!.user;
    expect(user).toContain("Diff stats");
    expect(user).toContain("2 file(s), +40/-6 lines");
    expect(prompts[0]!.system).toMatch(/Use the "Diff stats" line verbatim/i);
  });

  test("still offers the PR numbers it parsed out of the description and diff", async () => {
    const { provider, prompts } = recordingProvider();
    await generateExternalSummary(dossier(), "oss-outreach", provider);

    const user = prompts[0]!.user;
    expect(user).toContain("PRs referenced in the description/diff: #91");
    // The system prompt's ban is on inventing a number for a prior-PR snippet,
    // not on citing one that was handed over.
    expect(prompts[0]!.system).toMatch(
      /a `PR #N` that literally\s+appears in the material above/i,
    );
  });

  test("keeps a MEDIUM severity rather than flattening it to LOW", async () => {
    // enrichSeverityDots only aligns the emoji with the word; the calibration
    // lives entirely in the system prompt.
    const { provider, prompts } = recordingProvider();
    const summary = await generateExternalSummary(
      dossier(),
      "oss-outreach",
      provider,
    );

    expect(summary.content).toContain("🟡 MEDIUM");
    expect(summary.content).toContain("🟡 👀 **Careful pass**");
    expect(prompts[0]!.system).toContain("🟡 = MEDIUM");
    expect(prompts[0]!.user).toMatch(/do not default to LOW/i);
  });

  test("does not turn a cited PR number into a link", async () => {
    // enrichSummaryLinks never runs on this rail, so a referenced number stays
    // plain text and cannot masquerade as a server-verified deep link.
    const { provider } = recordingProvider();
    const summary = await generateExternalSummary(
      dossier(),
      "oss-outreach",
      provider,
    );
    expect(summary.content).toContain("Attribution: previous-prs PR #91");
    expect(summary.content).not.toContain("/pull/91");
  });
});

describe("collectReferencedPrs", () => {
  // The scan used to run over the raw unified diff, where #(\d{2,6}) matches
  // anything: a stylesheet's hex colours arrived as "PRs referenced" and were
  // then licensed for prior-PR citation in the summary.
  test("does not treat CSS hex colours as pull requests", () => {
    const body = "Tweaks the palette.";
    const diffLikeNoise = "+  color: #1a2b3c;\n+  background: #abc123;";
    expect(collectReferencedPrs(`${body}\n${diffLikeNoise}`, 99)).toEqual([]);
  });

  test("keeps a reference a person wrote in prose", () => {
    expect(collectReferencedPrs("Follows on from #412, reverts #98.", 99)).toEqual([412, 98]);
  });

  test("ignores a number glued to other text", () => {
    expect(collectReferencedPrs("see issue#412 and abc#98", 99)).toEqual([]);
  });

  test("never cites the pull request being summarised", () => {
    expect(collectReferencedPrs("supersedes #57", 57)).toEqual([]);
  });
});
