import { describe, expect, test } from "bun:test";
import {
  GX_AUTHOR_NOTES_HEADER,
  GX_AUTHOR_NOTES_MARKER,
  GX_PR_BODY_MARKER,
  appendAuthorNotes,
  ensurePrSummaryMarker,
  mergePrSummaryIntoBody,
  splitGeneratedPRBody,
} from "../src/github/pr-body";

const SAMPLE_SUMMARY = [
  GX_PR_BODY_MARKER,
  "",
  "> 👀 **Quick scan** — wires PR body updates",
  "",
  "## Blast Radius",
  "",
  "LOW (1 file, 1 area, +10/-2 lines).",
  "",
  "## Notable Changes",
  "",
  "- Update PR description instead of commenting",
  "  Attribution: heuristic server/src/github/pr-body.ts",
  "",
  "*Generated by GX.*",
].join("\n");

describe("pr-body merge helpers", () => {
  test("ensurePrSummaryMarker prepends ownership marker", () => {
    expect(ensurePrSummaryMarker("hello")).toBe(
      `${GX_PR_BODY_MARKER}\n\nhello`,
    );
    expect(ensurePrSummaryMarker(`${GX_PR_BODY_MARKER}\n\nhello`)).toBe(
      `${GX_PR_BODY_MARKER}\n\nhello`,
    );
  });

  test("splitGeneratedPRBody preserves human notes from a blank slate", () => {
    expect(splitGeneratedPRBody("")).toEqual({
      authorNotes: "",
      gxOwned: true,
    });
    expect(splitGeneratedPRBody("My hand-written notes")).toEqual({
      authorNotes: "My hand-written notes",
      gxOwned: false,
    });
    expect(splitGeneratedPRBody("Published by GX.\n\nold")).toEqual({
      authorNotes: "",
      gxOwned: true,
    });
  });

  test("splitGeneratedPRBody extracts Author Notes from a GX body", () => {
    const body = appendAuthorNotes(SAMPLE_SUMMARY, "Please review carefully.");
    const split = splitGeneratedPRBody(body);
    expect(split.gxOwned).toBe(true);
    expect(split.authorNotes).toBe("Please review carefully.");
  });

  test("mergePrSummaryIntoBody keeps author notes under the marker", () => {
    const merged = mergePrSummaryIntoBody(
      "Please review carefully.",
      SAMPLE_SUMMARY.replace(`${GX_PR_BODY_MARKER}\n\n`, ""),
    );
    expect(merged.startsWith(GX_PR_BODY_MARKER)).toBe(true);
    expect(merged).toContain(GX_AUTHOR_NOTES_MARKER);
    expect(merged).toContain(GX_AUTHOR_NOTES_HEADER);
    expect(merged).toContain("Please review carefully.");
    expect(merged).toContain("*Generated by GX.*");
  });

  test("mergePrSummaryIntoBody replaces a previous GX body and keeps notes", () => {
    const first = mergePrSummaryIntoBody("Keep me", SAMPLE_SUMMARY);
    const second = mergePrSummaryIntoBody(
      first,
      SAMPLE_SUMMARY.replace("wires PR body updates", "second pass"),
    );
    expect(second).toContain("second pass");
    expect(second).toContain("Keep me");
    expect(second.match(new RegExp(GX_AUTHOR_NOTES_MARKER, "g"))?.length).toBe(
      1,
    );
  });
});
