import { describe, expect, test } from "bun:test";
import {
  GX_AUTHOR_NOTES_HEADER,
  GX_AUTHOR_NOTES_MARKER,
  GX_PR_BODY_MARKER,
  appendAuthorNotes,
  ensurePrSummaryMarker,
  mergePrSummaryIntoBody,
  splitGeneratedPRBody,
  splitPrBody,
} from "../src/github/pr-body";

const SAMPLE_SUMMARY = [
  GX_PR_BODY_MARKER,
  "",
  "> 🟢 👀 **Quick scan** — wires PR body updates",
  "",
  "## Blast Radius",
  "",
  "🟢 LOW (1 file, 1 area, +10/-2 lines).",
  "",
  "## Notable Changes",
  "",
  "- Update PR description instead of commenting",
  "  Attribution: heuristic server/src/github/pr-body.ts",
  "",
  "*Generated by GX.*",
].join("\n");

const SAMPLE_SUMMARY_V2 = SAMPLE_SUMMARY.replace(
  "wires PR body updates",
  "second pass",
);

describe("pr-body merge helpers", () => {
  test("ensurePrSummaryMarker prepends ownership marker", () => {
    expect(ensurePrSummaryMarker("hello")).toBe(
      `${GX_PR_BODY_MARKER}\n\nhello`,
    );
    expect(ensurePrSummaryMarker(`${GX_PR_BODY_MARKER}\n\nhello`)).toBe(
      `${GX_PR_BODY_MARKER}\n\nhello`,
    );
  });

  test("splitPrBody treats blank and human-only bodies", () => {
    expect(splitPrBody("")).toEqual({ humanPrefix: "", gxOwned: false });
    expect(splitPrBody("My hand-written notes")).toEqual({
      humanPrefix: "My hand-written notes",
      gxOwned: false,
    });
    expect(splitPrBody("Published by GX.\n\nold")).toEqual({
      humanPrefix: "",
      gxOwned: true,
    });
  });

  test("splitPrBody extracts human prefix from legacy GX-first body", () => {
    const body = appendAuthorNotes(SAMPLE_SUMMARY, "Please review carefully.");
    const split = splitPrBody(body);
    expect(split.gxOwned).toBe(true);
    expect(split.humanPrefix).toBe("Please review carefully.");
  });

  test("splitPrBody keeps human text above a GX block", () => {
    const body = `Please review carefully.\n\n${SAMPLE_SUMMARY}`;
    expect(splitPrBody(body)).toEqual({
      humanPrefix: "Please review carefully.",
      gxOwned: true,
    });
  });

  test("mergePrSummaryIntoBody appends GX below existing human text", () => {
    const merged = mergePrSummaryIntoBody(
      "Please review carefully.",
      SAMPLE_SUMMARY.replace(`${GX_PR_BODY_MARKER}\n\n`, ""),
    );
    expect(merged.startsWith("Please review carefully.")).toBe(true);
    expect(merged).toContain(GX_PR_BODY_MARKER);
    expect(merged.indexOf("Please review carefully.")).toBeLessThan(
      merged.indexOf(GX_PR_BODY_MARKER),
    );
    expect(merged).toContain("*Generated by GX.*");
    expect(merged).not.toContain(GX_AUTHOR_NOTES_MARKER);
    expect(merged).not.toContain(GX_AUTHOR_NOTES_HEADER);
  });

  test("mergePrSummaryIntoBody re-update preserves human text above GX block", () => {
    const first = mergePrSummaryIntoBody("Keep me", SAMPLE_SUMMARY);
    const second = mergePrSummaryIntoBody(first, SAMPLE_SUMMARY_V2);
    expect(second.startsWith("Keep me")).toBe(true);
    expect(second).toContain("second pass");
    expect(second).not.toContain("wires PR body updates");
    expect(second.match(new RegExp(GX_PR_BODY_MARKER, "g"))?.length).toBe(1);
    expect(second.indexOf("Keep me")).toBeLessThan(
      second.indexOf(GX_PR_BODY_MARKER),
    );
  });

  test("mergePrSummaryIntoBody migrates legacy Author Notes above GX", () => {
    const legacy = appendAuthorNotes(SAMPLE_SUMMARY, "Keep me");
    const migrated = mergePrSummaryIntoBody(legacy, SAMPLE_SUMMARY_V2);
    expect(migrated.startsWith("Keep me")).toBe(true);
    expect(migrated).toContain("second pass");
    expect(migrated).not.toContain(GX_AUTHOR_NOTES_MARKER);
    expect(migrated).not.toContain(GX_AUTHOR_NOTES_HEADER);
  });

  test("mergePrSummaryIntoBody with empty body is GX-only", () => {
    expect(mergePrSummaryIntoBody("", SAMPLE_SUMMARY)).toBe(SAMPLE_SUMMARY);
    expect(mergePrSummaryIntoBody("   \n", SAMPLE_SUMMARY)).toBe(
      SAMPLE_SUMMARY,
    );
  });

  test("splitGeneratedPRBody remains a thin adapter over splitPrBody", () => {
    expect(splitGeneratedPRBody("notes")).toEqual({
      authorNotes: "notes",
      gxOwned: false,
    });
  });
});
