import { describe, expect, test } from "bun:test";
import {
  detectBlastRadiusLevel,
  enrichSeverityDots,
  SEVERITY_DOT,
} from "../src/summary/severity";

function sample(level: "LOW" | "MEDIUM" | "HIGH", withDots = false): string {
  const dot = withDots ? `${SEVERITY_DOT[level]} ` : "";
  return [
    `> ${withDots ? `${SEVERITY_DOT[level]} ` : ""}👀 **Quick scan** — triage note`,
    "",
    "## Blast Radius",
    "",
    `${dot}${level} (2 file(s), 1 area(s), +10/-1 lines).`,
    "Some risk note.",
    "",
    "## Notable Changes",
    "",
    "- something",
    "  Attribution: heuristic path.ts",
    "",
    "*Generated by GX.*",
  ].join("\n");
}

describe("detectBlastRadiusLevel", () => {
  test("reads level from Blast Radius section", () => {
    expect(detectBlastRadiusLevel(sample("MEDIUM"))).toBe("MEDIUM");
    expect(detectBlastRadiusLevel(sample("HIGH", true))).toBe("HIGH");
  });
});

describe("enrichSeverityDots", () => {
  test("adds green dots for LOW when missing", () => {
    const out = enrichSeverityDots(sample("LOW"));
    expect(out).toContain(`> ${SEVERITY_DOT.LOW} 👀 **Quick scan**`);
    expect(out).toContain(`${SEVERITY_DOT.LOW} LOW (2 file(s)`);
  });

  test("adds yellow dots for MEDIUM", () => {
    const out = enrichSeverityDots(sample("MEDIUM"));
    expect(out).toContain(`> ${SEVERITY_DOT.MEDIUM} 👀 **Quick scan**`);
    expect(out).toContain(`${SEVERITY_DOT.MEDIUM} MEDIUM (2 file(s)`);
  });

  test("adds red dots for HIGH", () => {
    const out = enrichSeverityDots(sample("HIGH"));
    expect(out).toContain(`> ${SEVERITY_DOT.HIGH} 👀 **Quick scan**`);
    expect(out).toContain(`${SEVERITY_DOT.HIGH} HIGH (2 file(s)`);
  });

  test("corrects mismatched dots to match Blast Radius level", () => {
    const wrong = sample("HIGH").replace(
      "> 👀",
      `> ${SEVERITY_DOT.LOW} 👀`,
    );
    // level line still HIGH without a dot; force wrong green on level
    const withWrongLevelDot = wrong.replace(
      "HIGH (2 file(s)",
      `${SEVERITY_DOT.LOW} HIGH (2 file(s)`,
    );
    const out = enrichSeverityDots(withWrongLevelDot);
    expect(out).toContain(`> ${SEVERITY_DOT.HIGH} 👀 **Quick scan**`);
    expect(out).toContain(`${SEVERITY_DOT.HIGH} HIGH (2 file(s)`);
    expect(out).not.toContain(SEVERITY_DOT.LOW);
  });

  test("is idempotent", () => {
    const once = enrichSeverityDots(sample("LOW"));
    const twice = enrichSeverityDots(once);
    expect(twice).toBe(once);
  });

  test("leaves text unchanged when no level is present", () => {
    const plain = "no blast radius here";
    expect(enrichSeverityDots(plain)).toBe(plain);
  });
});
