import { createHash } from "node:crypto";
import { describe, expect, test } from "bun:test";
import {
  blobPermalink,
  formatPRSummaryLink,
  githubPullFileDiffUrl,
  githubPullFileLineUrl,
  pullRequestNumberUrl,
} from "../src/github/line-links";
import { enrichSummaryLinks } from "../src/summary/enrich-links";

const PR_URL = "https://github.com/satoricorp/console/pull/38";

function diffId(file: string): string {
  return createHash("sha256").update(file).digest("hex");
}

describe("formatPRSummaryLink", () => {
  test("renders escaped HTML anchor", () => {
    expect(
      formatPRSummaryLink('a & "b"', "https://example.com/?q=a&b=1"),
    ).toBe(
      '<a href="https://example.com/?q=a&amp;b=1" target="_blank" rel="noopener noreferrer">a &amp; &quot;b&quot;</a>',
    );
  });

  test("returns plain text when url is empty", () => {
    expect(formatPRSummaryLink("plain", "")).toBe("plain");
  });

  test("always includes target=_blank and rel=noopener noreferrer", () => {
    const html = formatPRSummaryLink("label", "https://github.com/o/r/pull/1");
    expect(html).toContain('target="_blank"');
    expect(html).toContain('rel="noopener noreferrer"');
  });
});

describe("github link helpers", () => {
  test("builds file line, file diff, and blob permalinks", () => {
    const file = "server/src/github/pr-body.ts";
    const id = diffId(file);
    expect(githubPullFileLineUrl(PR_URL, file, 12)).toBe(
      `${PR_URL}/files#diff-${id}R12`,
    );
    expect(githubPullFileDiffUrl(PR_URL, file)).toBe(
      `${PR_URL}/files#diff-${id}`,
    );
    expect(blobPermalink(PR_URL, "abc123", file, 12)).toBe(
      `https://github.com/satoricorp/console/blob/abc123/${file}#L12`,
    );
    expect(pullRequestNumberUrl(PR_URL, 12)).toBe(
      "https://github.com/satoricorp/console/pull/12",
    );
  });

  test("returns null without a PR URL", () => {
    expect(githubPullFileLineUrl(null, "a.ts", 1)).toBeNull();
    expect(blobPermalink("", "sha", "a.ts", 1)).toBeNull();
  });
});

describe("enrichSummaryLinks", () => {
  const sample = [
    "> 🟢 👀 **Quick scan** — wires PR body updates",
    "",
    "## Blast Radius",
    "",
    "🟢 LOW (1 file, 1 area, +10/-2 lines).",
    "",
    "## Notable Changes",
    "",
    "- Update PR description in server/src/github/pr-body.ts",
    "  Attribution: codebase server/src/github/pr-body.ts",
    "- Follow-up from PR #12",
    "  Attribution: previous-prs PR #12",
    "- Outside file note in server/src/missing.ts:9",
    "  Attribution: heuristic server/src/missing.ts:9",
    "",
    "*Generated by TX.*",
  ].join("\n");

  const ctx = {
    prUrl: PR_URL,
    headSha: "deadbeef",
    hunks: [
      {
        file: "server/src/github/pr-body.ts",
        lineStart: 10,
        lineEnd: 40,
      },
    ],
    changedFiles: ["server/src/github/pr-body.ts"],
  };

  test("links notable change titles to PR hunk anchors", () => {
    const enriched = enrichSummaryLinks(sample, ctx);
    const want = githubPullFileLineUrl(
      PR_URL,
      "server/src/github/pr-body.ts",
      10,
    )!;
    expect(enriched).toContain(
      formatPRSummaryLink(
        "Update PR description in server/src/github/pr-body.ts",
        want,
      ),
    );
  });

  test("links attribution file paths in the PR diff", () => {
    const enriched = enrichSummaryLinks(sample, ctx);
    const want = githubPullFileLineUrl(
      PR_URL,
      "server/src/github/pr-body.ts",
      10,
    )!;
    expect(enriched).toContain(
      `Attribution: codebase ${formatPRSummaryLink("server/src/github/pr-body.ts", want)}`,
    );
  });

  // Previously this asserted that "PR #12" inside PR #38 became a link to
  // /pull/12. Nothing vouches for 12: prior-PR context rows carry a branch and
  // a head SHA and no PR number, so a number in a summary came from the model.
  // On satoricorp/tx#112 that turned the context labels [P1]/[P2] into links to
  // two real, unrelated pull requests.
  test("leaves an unvouched previous-PR number as plain text", () => {
    const enriched = enrichSummaryLinks(sample, ctx);
    expect(enriched).toContain("Attribution: previous-prs PR #12");
    expect(enriched).not.toContain(
      "https://github.com/satoricorp/console/pull/12",
    );
  });

  test("still links the PR being summarized when it is referenced by number", () => {
    const body = [
      "## Notable Changes",
      "",
      "- Self reference",
      "  Attribution: previous-prs PR #38",
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    expect(enriched).toContain(
      formatPRSummaryLink("PR #38", "https://github.com/satoricorp/console/pull/38"),
    );
  });

  test("uses blob permalinks for out-of-diff file refs", () => {
    const enriched = enrichSummaryLinks(sample, ctx);
    const want = blobPermalink(
      PR_URL,
      "deadbeef",
      "server/src/missing.ts",
      9,
    )!;
    expect(enriched).toContain(want);
    expect(enriched).toContain(
      formatPRSummaryLink("server/src/missing.ts:9", want),
    );
  });

  test("keeps plain text when PR URL is missing", () => {
    const enriched = enrichSummaryLinks(sample, {
      prUrl: null,
      headSha: null,
      hunks: ctx.hunks,
      changedFiles: ctx.changedFiles,
    });
    expect(enriched).not.toContain("<a href=");
    expect(enriched).toContain(
      "- Update PR description in server/src/github/pr-body.ts",
    );
    expect(enriched).toContain(
      "  Attribution: codebase server/src/github/pr-body.ts",
    );
  });

  test("is idempotent when links already exist", () => {
    const once = enrichSummaryLinks(sample, ctx);
    const twice = enrichSummaryLinks(once, ctx);
    expect(twice).toBe(once);
  });

  test("links flagged notable bullets", () => {
    const body = [
      "## Notable Changes",
      "",
      "- ⚠ auth change in server/src/github/pr-body.ts",
      "  Attribution: heuristic",
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    expect(enriched).toContain("- ⚠ <a href=");
    expect(enriched).toContain("auth change in server/src/github/pr-body.ts</a>");
    expect(enriched).toContain('target="_blank"');
    expect(enriched).toContain('rel="noopener noreferrer"');
    // Bare "heuristic" expands to the concrete file:line from the bullet/hunk.
    const want = githubPullFileLineUrl(
      PR_URL,
      "server/src/github/pr-body.ts",
      10,
    )!;
    expect(enriched).toContain(
      `Attribution: heuristic ${formatPRSummaryLink("server/src/github/pr-body.ts:10", want)}`,
    );
  });

  test("expands bare codebase attribution to file:line from the bullet", () => {
    const body = [
      "## Notable Changes",
      "",
      "- Wire PR body updates in server/src/github/pr-body.ts",
      "  Attribution: codebase",
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    const want = githubPullFileLineUrl(
      PR_URL,
      "server/src/github/pr-body.ts",
      10,
    )!;
    expect(enriched).toContain(
      `Attribution: codebase ${formatPRSummaryLink("server/src/github/pr-body.ts:10", want)}`,
    );
    expect(enriched).not.toMatch(/Attribution: codebase$/m);
  });

  test("does not expand a bare previous-prs attribution into an unvouched PR link", () => {
    const body = [
      "## Notable Changes",
      "",
      "- Follow-up from PR #12",
      "  Attribution: previous-prs",
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    expect(enriched).toContain("Attribution: previous-prs");
    expect(enriched).not.toContain(
      "https://github.com/satoricorp/console/pull/12",
    );
  });

  test("upgrades anchors missing target=_blank", () => {
    const body = [
      "## Notable Changes",
      "",
      '- <a href="https://github.com/satoricorp/console/pull/38/files#diff-abc">title</a>',
      '  Attribution: codebase <a href="https://example.com/file">server/src/github/pr-body.ts</a>',
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    expect(enriched).toContain('target="_blank"');
    expect(enriched).toContain('rel="noopener noreferrer"');
    expect(enriched).not.toMatch(/<a href="[^"]+">/);
  });

  test("linkifies path tokens inside attribution notes", () => {
    const body = [
      "## Notable Changes",
      "",
      "- Update handler",
      "  Attribution: codebase see server/src/github/pr-body.ts for the patch",
      "",
      "*Generated by TX.*",
    ].join("\n");
    const enriched = enrichSummaryLinks(body, ctx);
    const want = githubPullFileLineUrl(
      PR_URL,
      "server/src/github/pr-body.ts",
      10,
    )!;
    expect(enriched).toContain(formatPRSummaryLink("server/src/github/pr-body.ts", want));
  });
});

describe("placeholder line refs", () => {
  const ctx = {
    prUrl: PR_URL,
    headSha: "9b7b7743a006e651af6fb2897a191e208298bb1a",
    repoFullName: "satoricorp/console",
    changedFiles: ["server/src/context/broker.ts"],
    hunks: [],
  } as never;

  function enrich(attribution: string): string {
    return enrichSummaryLinks(
      ["## Notable Changes", "", "- Did a thing.", `  Attribution: ${attribution}`].join("\n"),
      ctx,
    );
  }

  // The prompt describes references as `path:line`; models copied that literally
  // and the enricher built links to a path named ".../broker.ts:line", which
  // 404s. Every attribution on every summary carried one.
  test("drops a copied `path:line` placeholder instead of linking to it", () => {
    const enriched = enrich("codebase server/src/context/broker.ts:line");
    expect(enriched).not.toContain("broker.ts:line");
    expect(enriched).toContain("server/src/context/broker.ts");
    expect(enriched).not.toContain("/blob/9b7b7743a006e651af6fb2897a191e208298bb1a/server/src/context/broker.ts:line");
  });

  test("keeps a real line number", () => {
    const enriched = enrich("codebase server/src/context/broker.ts:42");
    expect(enriched).toContain("server/src/context/broker.ts:42");
  });
});

describe("cross-repository PR references", () => {
  const ctx = {
    prUrl: "https://github.com/satoricorp/console/pull/57",
    headSha: "9b7b7743a006e651af6fb2897a191e208298bb1a",
    repoFullName: "satoricorp/console",
    changedFiles: ["server/src/app.ts"],
    hunks: [],
  } as never;

  function enrich(attribution: string): string {
    return enrichSummaryLinks(
      ["## Notable Changes", "", "- Did a thing.", `  Attribution: ${attribution}`].join("\n"),
      ctx,
    );
  }

  // Pull request numbers are per-repository, so matching on the number alone
  // resolved another project's #57 to this project's #57 — a real, unrelated
  // page presented as the cited source.
  test("does not link another repository's pull request", () => {
    const enriched = enrich("previous-prs otherorg/otherrepo#57");
    expect(enriched).not.toContain("<a ");
    expect(enriched).toContain("otherorg/otherrepo#57");
  });

  test("still links this repository's own pull request", () => {
    const enriched = enrich("previous-prs satoricorp/console#57");
    expect(enriched).toContain("github.com/satoricorp/console/pull/57");
  });
});
