import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import app from "../src/app";
import { getSql, runMigrations } from "../src/db";
import { createMockProvider } from "../src/llm/provider";
import { generateSummary } from "../src/summary/generate";
import { validateSummary, REQUIRED_SECTIONS } from "../src/summary/validate";
import { authHeaders, installTestAuth } from "./auth";
import { describeDb } from "./db-gate";

// Unique per process run. bookmarks carries a UNIQUE index on
// (user_id, repo_full_name, branch_name) (migration 018), so a fixed user id
// seeds cleanly exactly once per database and then fails with 23505 on every
// later run. Tests must not assume the database was just created.
const summaryUserId = `summary-test-user-${crypto.randomUUID()}`;

describe("validateSummary", () => {
  const validSummary = [
    "> 🟢 👀 **Quick scan** — standard change; skim the notable changes.",
    "",
    "Add capture upload path for WP-1b.",
    "",
    "## Blast Radius",
    "",
    "🟢 LOW (2 file(s), 1 area(s), +10/-1 lines).",
    "CLI upload only; no production runtime path is changed.",
    "",
    "## Notable Changes",
    "",
    "- internal/capture/extract/upload.go adds the upload path",
    "  Attribution: agent-sessions internal/capture/extract/upload.go",
    "- test fixtures cover the happy path",
    "  Attribution: heuristic internal/capture/extract/upload_test.go",
    "",
    "*Generated by TX.*",
  ].join("\n");

  test("accepts valid rich summary with required sections", () => {
    const result = validateSummary(validSummary);
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.lineCount).toBeLessThanOrEqual(40);
    }
  });

  test("rejects more than 40 lines", () => {
    const lines = validSummary.split("\n");
    const tooLong = [...lines, ...Array.from({ length: 30 }, (_, i) => `extra ${i}`)].join("\n");
    const result = validateSummary(tooLong);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBe("too_many_lines");
    }
  });

  test("rejects missing sections", () => {
    for (const section of REQUIRED_SECTIONS) {
      const lines = validSummary
        .split("\n")
        .filter((line) => normalizeHeading(line.trim()) !== section.toLowerCase());
      const result = validateSummary(lines.join("\n"));
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error).toBe("missing_section");
        expect(result.detail).toBe(section);
      }
    }
  });

  test("rejects missing attribution", () => {
    const withoutAttribution = validSummary
      .split("\n")
      .filter((line) => !line.trim().startsWith("Attribution:"))
      .join("\n");
    const result = validateSummary(withoutAttribution);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBe("missing_attribution");
    }
  });

  test("rejects missing Generated by TX footer", () => {
    const withoutFooter = validSummary.replace("*Generated by TX.*", "");
    const result = validateSummary(withoutFooter);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBe("missing_footer");
    }
  });

  test("rejects word brief case-insensitively", () => {
    const withBrief = validSummary.replace("standard change", "brief change");
    const result = validateSummary(withBrief);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBe("contains_brief");
    }
  });

  test("accepts plain section headings without markdown hashes", () => {
    const plain = validSummary
      .split("\n")
      .map((line) => line.replace(/^##\s+/, ""))
      .join("\n");
    expect(validateSummary(plain).ok).toBe(true);
  });
});

function normalizeHeading(line: string): string {
  return line
    .replace(/^#+\s*/, "")
    .replace(/^\*\*(.+)\*\*$/, "$1")
    .replace(/:$/, "")
    .trim()
    .toLowerCase();
}

describeDb("generateSummary integration", () => {
  let orgId: string;
  let bookmarkId: string;
  let eventId: string;

  beforeAll(async () => {
    delete process.env.OPENAI_API_KEY;
    installTestAuth();
    await runMigrations();

    const db = getSql();
    const now = Date.now();

    const [org] = await db<{ id: string }[]>`
      INSERT INTO orgs (plan, created_at_ms)
      VALUES ('free', ${now})
      RETURNING id
    `;
    orgId = org.id;

    const [event] = await db<{ id: string }[]>`
      INSERT INTO pr_events (
        created_at_ms, tx_version, head_commit_id, payload, org_id, user_id, repo_root_path
      ) VALUES (
        ${now},
        '0.1.0-test',
        'cafebabe',
        ${JSON.stringify({
          refRange: "main..HEAD",
          fileStats: { filesChanged: 2, insertions: 10, deletions: 1 },
          intentCandidates: ["Wire PR Summary generator"],
        })}::jsonb,
        ${orgId},
        ${summaryUserId},
        '/Users/joe/git/tx'
      )
      RETURNING id
    `;
    eventId = event.id;

    const [bookmark] = await db<{ id: string }[]>`
      INSERT INTO bookmarks (
        user_id, repo_full_name, branch_name, published_at_ms, updated_at_ms, org_id, latest_event_id
      ) VALUES (
        ${summaryUserId},
        'acme/tx',
        'feat/summary',
        ${now},
        ${now},
        ${orgId},
        ${eventId}
      )
      RETURNING id
    `;
    bookmarkId = bookmark.id;

    await db`
      INSERT INTO hunk_links (
        org_id, event_id, file, line_start, line_end,
        session_id, match_tier, confidence, authorship, tool, model
      ) VALUES (
        ${orgId},
        ${eventId},
        'server/src/summary/generate.ts',
        1,
        40,
        'summary-session-1',
        1,
        0.95,
        'agent',
        'cursor',
        'gpt-4'
      )
    `;

    const [raw] = await db<{ id: string }[]>`
      INSERT INTO sessions_raw (
        org_id, session_id, tool, model, content, captured_at_ms
      ) VALUES (
        ${orgId},
        'summary-session-1',
        'cursor',
        'gpt-4',
        '[cursor] edit server/src/summary/generate.ts\npatch body\n[cursor] message done',
        ${now}
      )
      RETURNING id
    `;

    await db`
      INSERT INTO session_events (
        org_id, session_id, tool, model, ts, event_type, file_path,
        content_hash, raw_id, raw_line
      ) VALUES (
        ${orgId},
        'summary-session-1',
        'cursor',
        'gpt-4',
        ${now + 1},
        'edit',
        'server/src/summary/generate.ts',
        'hash-summary-test',
        ${raw.id},
        1
      )
    `;
  });

  afterAll(async () => {
  });

  test("mock generate inserts summaries and summary_events", async () => {
    const db = getSql();
    const result = await generateSummary(db, {
      orgId,
      eventId,
      provider: createMockProvider("Wire PR Summary generator"),
    });

    expect(result.summaryId).toBeTruthy();
    expect(result.bookmarkId).toBe(bookmarkId);
    expect(result.eventId).toBe(eventId);
    expect(result.lineCount).toBeLessThanOrEqual(40);
    expect(validateSummary(result.content).ok).toBe(true);

    const [summary] = await db<{ content: string; model: string }[]>`
      SELECT content, model FROM summaries WHERE id = ${result.summaryId}
    `;
    expect(summary.model).toBe("mock");
    expect(summary.content).toContain("Blast Radius");
    expect(summary.content).toContain("Notable Changes");
    expect(summary.content).toContain("Attribution:");

    const events = await db<{ kind: string }[]>`
      SELECT kind FROM summary_events WHERE summary_id = ${result.summaryId}
    `;
    expect(events.some((e) => e.kind === "view")).toBe(true);
  });

  // The standalone POST /v1/summaries/generate route was removed (production
  // summaries flow through the webhook and publish paths); these pin the same
  // contract at the function boundary those paths call.
  test("generateSummary returns summary metadata", async () => {
    const db = getSql();
    const result = await generateSummary(db, {
      orgId,
      userId: summaryUserId,
      bookmarkId,
      provider: createMockProvider(),
    });

    expect(result.bookmarkId).toBe(bookmarkId);
    expect(result.eventId).toBe(eventId);
    expect(result.lineCount).toBeLessThanOrEqual(40);
    expect(result.summaryId).toBeTruthy();
  });

  test("rejects when the bookmark is missing", async () => {
    const db = getSql();
    await expect(
      generateSummary(db, {
        orgId,
        userId: summaryUserId,
        bookmarkId: "00000000-0000-0000-0000-000000000099",
      }),
    ).rejects.toThrow(/bookmark not found/);
  });
});
