export const REQUIRED_SECTIONS = [
  "Blast Radius",
  "Notable Changes",
] as const;

export type SummaryValidationError =
  | "too_many_lines"
  | "missing_section"
  | "missing_attribution"
  | "missing_footer"
  | "contains_brief";

export type SummaryValidationResult =
  | { ok: true; lineCount: number }
  | { ok: false; error: SummaryValidationError; detail?: string };

const maxSummaryLines = 40;

function normalizeHeading(line: string): string {
  return line
    .replace(/^#+\s*/, "")
    .replace(/^\*\*(.+)\*\*$/, "$1")
    .replace(/:$/, "")
    .trim()
    .toLowerCase();
}

function sectionPresent(text: string, heading: string): boolean {
  const target = heading.toLowerCase();
  for (const line of text.split("\n")) {
    const normalized = normalizeHeading(line.trim());
    if (normalized === target) {
      return true;
    }
  }
  return false;
}

/** Validate rich PR Summary: required sections, attributions, footer, no "brief". */
export function validateSummary(text: string): SummaryValidationResult {
  const trimmed = text.trim();
  if (!trimmed) {
    return { ok: false, error: "missing_section", detail: "Blast Radius" };
  }

  if (/\bbrief\b/i.test(trimmed)) {
    return { ok: false, error: "contains_brief" };
  }

  const lines = trimmed.split("\n");
  if (lines.length > maxSummaryLines) {
    return { ok: false, error: "too_many_lines", detail: String(lines.length) };
  }

  for (const section of REQUIRED_SECTIONS) {
    if (!sectionPresent(trimmed, section)) {
      return { ok: false, error: "missing_section", detail: section };
    }
  }

  if (!/^\s*Attribution:/im.test(trimmed)) {
    return { ok: false, error: "missing_attribution" };
  }

  if (!/\*Generated by GX\./i.test(trimmed)) {
    return { ok: false, error: "missing_footer" };
  }

  return { ok: true, lineCount: lines.length };
}

export function assertValidSummary(text: string): void {
  const result = validateSummary(text);
  if (!result.ok) {
    const detail = result.detail ? `: ${result.detail}` : "";
    throw new Error(`Invalid PR Summary (${result.error}${detail})`);
  }
}
