import type { ExtractContext } from "../../summary/generate";
import {
  formatBucketPromptSections,
  formatContextManifestLine,
  type ContextBucket,
  type ContextManifestEntry,
  type ContextSnippet,
} from "../../context/broker";

export const PR_SUMMARY_SYSTEM_PROMPT = `You write PR Summaries for GitHub pull request descriptions.

GX Cloud writes exactly one rich summary into the PR body. Match this format:

> 🟢 👀 **Quick scan** — <one short triage reason>

<one paragraph overview of what changed and why>

## Blast Radius

🟢 LOW (<N> file(s), <N> area(s), +X/-Y lines).
<one short sentence on customer/runtime risk>

## Notable Changes

- <most important change; include path when known>
  Attribution: <agent-sessions|codebase|previous-prs|docs|heuristic> <concrete ref>
- <next important change>
  Attribution: …

*Generated by GX.*

Rules:
- At most 40 lines total including blank lines
- Be concise; prefer 3–7 Notable Changes bullets
- Severity dots (same color on Quick scan and Blast Radius level):
  - 🟢 = LOW (safe to skim / contained)
  - 🟡 = MEDIUM (needs a careful pass)
  - 🔴 = HIGH (risky; prioritize review)
- Every Notable Changes bullet must include an Attribution line
- Attribution must name a concrete source — never a bare kind alone:
  - codebase / heuristic: \`path\` or \`path:line\` from the change or Codebase context
  - agent-sessions: session id and/or \`path:line\` from hunk links
  - previous-prs: \`PR #N\` (or owner/repo#N)
  - docs: doc path or title from Independent resources
- Never use the word "brief"
- Only cite indexed buckets that appear in "Context provided"; never name a bucket with provided=0
- Prefer concrete files and behaviors over vague claims
- Do not invent GitHub deep links; plain path / path:line / PR #N text is fine`;

const maxPatchCharsPerRevision = 3000;
const maxPatchCharsTotal = 12000;

export function buildPRSummaryUserPrompt(ctx: ExtractContext): string {
  const lines: string[] = [
    `Repository root: ${ctx.repoRootPath ?? "unknown"}`,
    `Head commit: ${ctx.headCommitId ?? "unknown"}`,
    `Ref range: ${ctx.refRange ?? "unknown"}`,
  ];

  if (ctx.fileStats) {
    lines.push(`File stats: ${JSON.stringify(ctx.fileStats)}`);
  }

  if (ctx.intentCandidates.length > 0) {
    lines.push(`Intent candidates: ${JSON.stringify(ctx.intentCandidates)}`);
  }

  const revisions = ctx.publishedRevisions ?? [];
  if (revisions.length > 0) {
    lines.push("Published revisions:");
    let patchBudget = maxPatchCharsTotal;
    for (const revision of revisions.slice(0, 10)) {
      const title = revision.description?.split("\n")[0]?.trim() || "(no description)";
      const branch = revision.branchName ? ` [${revision.branchName}]` : "";
      lines.push(`- ${title}${branch}`);
      if (revision.files.length > 0) {
        lines.push(`  Files: ${revision.files.slice(0, 30).join(", ")}`);
      }
      if (revision.patch && patchBudget > 0) {
        const excerpt = revision.patch.slice(
          0,
          Math.min(maxPatchCharsPerRevision, patchBudget),
        );
        patchBudget -= excerpt.length;
        lines.push("  Patch excerpt:");
        lines.push("```diff");
        lines.push(excerpt);
        if (excerpt.length < revision.patch.length) {
          lines.push("[patch truncated]");
        }
        lines.push("```");
      }
    }
  }

  const publishedSessions = ctx.publishedSessions ?? [];
  if (publishedSessions.length > 0) {
    lines.push("Captured agent sessions linked to this change:");
    for (const session of publishedSessions.slice(0, 8)) {
      lines.push(
        `- ${session.sessionId || "session"} command=${session.command ?? "?"} requests=${session.requestCount}`,
      );
    }
  }

  if (ctx.hunkLinks.length > 0) {
    lines.push("Hunk links (file, lines, session, tier, authorship):");
    for (const link of ctx.hunkLinks.slice(0, 40)) {
      lines.push(
        `- ${link.file}:${link.lineStart}-${link.lineEnd} session=${link.sessionId} tier=${link.matchTier} auth=${link.authorship} tool=${link.tool ?? "?"}`,
      );
    }
    if (ctx.hunkLinks.length > 40) {
      lines.push(`- … ${ctx.hunkLinks.length - 40} more hunks omitted`);
    }
  }

  if (ctx.sessionEvents.length > 0) {
    lines.push("Session events (sample):");
    for (const event of ctx.sessionEvents.slice(0, 20)) {
      lines.push(
        `- ${event.sessionId} ${event.eventType} ${event.filePath ?? ""} line=${event.rawLine}`,
      );
    }
  }

  if (ctx.indexSnippets && ctx.indexSnippets.length > 0) {
    const byBucket = new Map<ContextBucket, ContextSnippet[]>();
    const manifest = {
      "agent-sessions": { provided: 0, chars: 0 },
      codebase: { provided: 0, chars: 0 },
      "previous-prs": { provided: 0, chars: 0 },
      docs: { provided: 0, chars: 0 },
    } as Record<ContextBucket, ContextManifestEntry>;
    for (const snip of ctx.indexSnippets) {
      const bucket = (snip.bucket as ContextBucket | undefined) ?? "codebase";
      const list = byBucket.get(bucket) ?? [];
      list.push({
        id: snip.id,
        citationId: snip.id,
        bucket,
        sourceKind: snip.sourceKind ?? "unknown",
        text: snip.text,
        score: snip.score,
        file: snip.file,
      });
      byBucket.set(bucket, list);
      manifest[bucket] = {
        provided: list.length,
        chars: list.reduce((s, x) => s + x.text.length, 0),
      };
    }
    const buckets = {
      "agent-sessions": byBucket.get("agent-sessions") ?? [],
      codebase: byBucket.get("codebase") ?? [],
      "previous-prs": byBucket.get("previous-prs") ?? [],
      docs: byBucket.get("docs") ?? [],
    };
    lines.push(formatContextManifestLine(manifest));
    lines.push(...formatBucketPromptSections(buckets));
  }

  lines.push("", "Write the PR Summary now.");
  return lines.join("\n");
}
